spring:
  application:
    name: department-service
  datasource:
    url: jdbc:mysql://localhost:3306/payment_system
    username: devuser
    password: devuser
    hikari:
        connection-timeout: 20000
        maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  transaction:
    default-timeout: 30
    rollback-on-commit-failure: true

  config:
    import: "optional:configserver:http://localhost:8088"
server:
  port: 8081